Repository riok/mapperly, pull requests merged in 2023-01, with the labels that each got.

#237 docs: improve tests documentation
  docs/docs/98-contributing/02-tests.md
Labels: documentation

#238 chore: update code analyzer dependencies
  docs/docs/98-contributing/03-debugging.md
  src/Riok.Mapperly.Abstractions/Riok.Mapperly.Abstractions.csproj
  src/Riok.Mapperly/Helpers/DebuggerUtil.cs
  src/Riok.Mapperly/MapperGenerator.cs
  src/Riok.Mapperly/Riok.Mapperly.csproj
Labels: dependencies, .NET

#239 feat: constructor mapping support for MapProperty attribute
  .gitignore
  docs/docs/02-configuration/07-ctor-mappings.md
  src/Riok.Mapperly/AnalyzerReleases.Shipped.md
  src/Riok.Mapperly/Descriptors/MappingBodyBuilder/NewInstanceObjectPropertyMappingBodyBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilder/NewInstanceMappingBuilderContext.cs
  src/Riok.Mapperly/Descriptors/Mappings/PropertyMappings/ConstructorParameterMapping.cs
  src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyConstructorResolverTest.cs
Labels: enhancement
