Repository riok/mapperly, pull requests merged in 2024-09, with the labels that each got.

#1483 1476 strings in enum value attribute
  docs/docs/configuration/enum.mdx
  src/Riok.Mapperly.Abstractions/MapEnumValueAttribute.cs
  src/Riok.Mapperly.Abstractions/PublicAPI.Shipped.txt
  src/Riok.Mapperly/AnalyzerReleases.Shipped.md
  src/Riok.Mapperly/Configuration/EnumValueMappingConfiguration.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/EnumMappingDiagnosticReporter.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/EnumToEnumMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/EnumToStringMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/MappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/StringToEnumMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumFromStringSwitchMapping.cs
  src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumToStringMapping.cs
  src/Riok.Mapperly/Descriptors/SymbolAccessor.cs
  src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs
  test/Riok.Mapperly.Tests/Mapping/EnumToEnumExplicitMapTest.cs
  test/Riok.Mapperly.Tests/Mapping/EnumToStringExplicitMapTest.cs
  test/Riok.Mapperly.Tests/Mapping/StringToEnumExplicitMapTest.cs
Labels: enhancement, breaking-change

#1490 upgrade dotnet version and allow roll forward to the latest minor
  global.json
Labels: no-changelog

#1498 Support inlining of method with generic type arguments
  src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs
  test/Riok.Mapperly.Tests/Helpers/InlineExpressionRewriterTest.cs
Labels: bug

#1486 1470 enum naming strategy
  docs/docs/configuration/enum.mdx
  src/Riok.Mapperly.Abstractions/EnumNamingStrategy.cs
  src/Riok.Mapperly.Abstractions/MapEnumAttribute.cs
  src/Riok.Mapperly.Abstractions/MapperAttribute.cs
  src/Riok.Mapperly.Abstractions/PublicAPI.Shipped.txt
  src/Riok.Mapperly/AnalyzerReleases.Shipped.md
  src/Riok.Mapperly/Configuration/EnumConfiguration.cs
  src/Riok.Mapperly/Configuration/EnumMappingConfiguration.cs
  src/Riok.Mapperly/Configuration/MapperConfiguration.cs
  src/Riok.Mapperly/Configuration/MapperConfigurationMerger.cs
  src/Riok.Mapperly/Configuration/MapperConfigurationReader.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/EnumMappingDiagnosticReporter.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/EnumToEnumMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/EnumToStringMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/StringToEnumMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumFallbackValueMapping.cs
  src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumFromStringSwitchMapping.cs
  src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumMemberMapping.cs
  src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumToStringMapping.cs
  src/Riok.Mapperly/Descriptors/SymbolAccessor.cs
  src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs
  src/Riok.Mapperly/Helpers/EnumNamingStrategyHelper.cs
  src/Riok.Mapperly/Helpers/MemberNamingUtil.cs
  test/Riok.Mapperly.Tests/Helpers/MemberNamingUtilTest.cs
  test/Riok.Mapperly.Tests/Mapping/EnumFallbackValueTest.cs
  test/Riok.Mapperly.Tests/Mapping/EnumNamingStrategyTest.cs
Labels: enhancement

#1507 feat: support enum naming strategies for DescriptionAttribute and Enu…
  docs/docs/configuration/enum.mdx
  src/Riok.Mapperly.Abstractions/EnumNamingStrategy.cs
  src/Riok.Mapperly.Abstractions/MapperAttribute.cs
  src/Riok.Mapperly.Abstractions/PublicAPI.Shipped.txt
  src/Riok.Mapperly/AnalyzerReleases.Shipped.md
  src/Riok.Mapperly/Configuration/ComponentModelDescriptionAttributeConfiguration.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/EnumMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/EnumToEnumMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/EnumToStringMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/StringToEnumMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumFallbackValueMapping.cs
  src/Riok.Mapperly/Descriptors/SymbolAccessor.cs
  src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs
  src/Riok.Mapperly/Helpers/EnumNamingStrategyHelper.cs
  test/Riok.Mapperly.Tests/Mapping/EnumNamingStrategyTest.cs
  test/Riok.Mapperly.Tests/Mapping/EnumToStringExplicitMapTest.cs
  test/Riok.Mapperly.Tests/Mapping/StringToEnumExplicitMapTest.cs
Labels: enhancement

#1497 chore: replace PublicApiAnalyzer with snapshot test
  docs/docs/contributing/common-tasks.md
  src/Riok.Mapperly.Abstractions/PublicAPI.Shipped.txt
  src/Riok.Mapperly.Abstractions/PublicAPI.Unshipped.txt
  src/Riok.Mapperly.Abstractions/Riok.Mapperly.Abstractions.csproj
  test/Riok.Mapperly.Abstractions.Tests/ModuleInitializer.cs
  test/Riok.Mapperly.Abstractions.Tests/PublicApiTest.cs
  test/Riok.Mapperly.Abstractions.Tests/Riok.Mapperly.Abstractions.Tests.csproj
  test/Riok.Mapperly.Abstractions.Tests/_snapshots/PublicApiTest.PublicApiHasNotChanged.verified.cs
Labels: no-changelog

#1506 run integration tests with .net 9.0
  .github/workflows/test.yml
  test/Riok.Mapperly.IntegrationTests/BaseMapperTest.cs
  test/Riok.Mapperly.IntegrationTests/Helpers/Versions.cs
  test/Riok.Mapperly.IntegrationTests/ProjectionMapperTest.cs
  test/Riok.Mapperly.IntegrationTests/Riok.Mapperly.IntegrationTests.csproj
  test/Riok.Mapperly.IntegrationTests/_snapshots/ProjectionMapperTest.ProjectionShouldTranslateToQuery_NET9_0.verified.sql
Labels: no-changelog

#1508 upgrade path to regexp
  docs/package-lock.json
  docs/package.json
Labels: no-changelog
