Repository riok/mapperly, pull requests merged in 2024-10, with the labels that each got.

#1515 docs: add security headers
  .editorconfig
  docs/static/_headers
Labels: no-changelog

#1517 fix issue
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs
Labels: no-changelog

#1524 docs: add 'buy us a coffee' link
  docs/docusaurus.config.js
  docs/src/components/NavbarItems/CoffeeNavbarItem/index.tsx
  docs/src/theme/NavbarItem/ComponentTypes.js
Labels: no-changelog

#1518 improve fullnameof and allow namespaced and nested types
  docs/docs/configuration/flattening.md
  src/Riok.Mapperly/Configuration/AttributeDataAccessor.cs
  src/Riok.Mapperly/Configuration/IMemberPathConfiguration.cs
  src/Riok.Mapperly/Configuration/MemberMappingConfiguration.cs
  src/Riok.Mapperly/Configuration/MemberPathConstants.cs
  src/Riok.Mapperly/Configuration/MemberValueMappingConfiguration.cs
  src/Riok.Mapperly/Configuration/MembersMappingConfiguration.cs
  src/Riok.Mapperly/Configuration/NestedMembersMappingConfiguration.cs
  src/Riok.Mapperly/Configuration/StringMemberPath.cs
  src/Riok.Mapperly/Configuration/SymbolMemberPath.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/IgnoredMembersBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingState.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingStateBuilder.cs
  src/Riok.Mapperly/Descriptors/SimpleMappingBuilderContext.cs
  src/Riok.Mapperly/Descriptors/SymbolAccessor.cs
  src/Riok.Mapperly/Helpers/OperationExtensions.cs
  src/Riok.Mapperly/Symbols/CompilationContext.cs
  src/Riok.Mapperly/Symbols/Members/ConstructorParameterMember.cs
  src/Riok.Mapperly/Symbols/Members/FieldMember.cs
  src/Riok.Mapperly/Symbols/Members/IMappableMember.cs
  src/Riok.Mapperly/Symbols/Members/ParameterSourceMember.cs
  src/Riok.Mapperly/Symbols/Members/PropertyMember.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs
Labels: enhancement

#1531 ignore capacity related diagnostics for system collection types when mapping from custom type
  src/Riok.Mapperly/Descriptors/Enumerables/Capacity/CapacityMemberSetter.cs
  src/Riok.Mapperly/Descriptors/Enumerables/Capacity/CapacitySetterBuilder.cs
  src/Riok.Mapperly/Descriptors/Enumerables/Capacity/EnsureCapacityMethodSetter.cs
  src/Riok.Mapperly/Descriptors/Enumerables/Capacity/ICapacityMemberSetter.cs
  src/Riok.Mapperly/Descriptors/Enumerables/Capacity/ICapacitySetter.cs
  src/Riok.Mapperly/Descriptors/Enumerables/Capacity/NonEnumeratedCapacitySetter.cs
  src/Riok.Mapperly/Descriptors/Enumerables/Capacity/SimpleCapacitySetter.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/IMembersBuilderContext.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingState.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/EnumerableMappingBodyBuilder.cs
  src/Riok.Mapperly/Helpers/SymbolExtensions.cs
  test/Riok.Mapperly.Tests/Mapping/EnumerableCustomTest.cs
Labels: bug

#1535 Removes the obsolete attribute from `MapProperty.ctor(string[], string[]`)
  docs/docs/breaking-changes/4-0.md
  src/Riok.Mapperly.Abstractions/MapPropertyAttribute.cs
  test/Riok.Mapperly.Abstractions.Tests/_snapshots/PublicApiTest.PublicApiHasNotChanged.verified.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNestedTest.cs
Labels: bug

#1536 allow assignments of MapValue constant value types to nullable value types
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/SourceValueBuilder.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyValueMethodTest.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyValueTest.cs
Labels: bug

#1538 handle nullable value types with MapValueAttribute and methods correct
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/SourceValueBuilder.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyValueMethodTest.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyValueTest.cs
Labels: bug

#1539 add hint to clarify abstractions scope runtime only works within same project
  docs/docs/getting-started/installation.mdx
  src/Riok.Mapperly.Abstractions/MapperAttribute.cs
Labels: documentation

#1555 add roslyn 4.11 as target
  .csharpierrc.yaml
  benchmarks/Riok.Mapperly.Benchmarks/Riok.Mapperly.Benchmarks.csproj
  build/package.sh
  src/Riok.Mapperly/Riok.Mapperly.Roslyn4.11.props
  src/Riok.Mapperly/Riok.Mapperly.csproj
  test/Riok.Mapperly.Tests/Riok.Mapperly.Tests.csproj
Labels: enhancement

#1556 Correct analysis of property member accessors
  src/Riok.Mapperly/Symbols/Members/PropertyMember.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyInitPropertyTest.cs
Labels: bug

#1559 simplify could not generate mapping exception syntax
  src/Riok.Mapperly/Descriptors/Mappings/UnimplementedMapping.cs
  src/Riok.Mapperly/Emit/Syntax/SyntaxFactoryHelper.Exception.cs
  src/Riok.Mapperly/Emit/Syntax/SyntaxIndentationExtensions.cs
  test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
  test/Riok.Mapperly.Tests/Mapping/ValueTupleTest.cs
  test/Riok.Mapperly.Tests/_snapshots/EnumerableTest.NullableElementMappingWithPrivateConstructorShouldDiagnostic#Mapper.g.verified.cs
  test/Riok.Mapperly.Tests/_snapshots/EnumerableTest.NullableElementMappingWithPrivateConstructorShouldDiagnostic.verified.txt
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyConstructorResolverTest.ClassToClassPrivateCtorShouldDiagnostic#Mapper.g.verified.cs
Labels: bug

#1558 Fix inconsistent handling of mixed nullable contexts
  src/Riok.Mapperly/Descriptors/MappingBuilderContext.cs
  src/Riok.Mapperly/Descriptors/TypeMappingKey.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNullableTest.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyNullableTest.MixedNullableContextsWithDerivedTypesShouldWork#Mapper.g.verified.cs
Labels: bug

#1560 allow multiple MapProperty attributes for the same target member
  src/Riok.Mapperly/Configuration/IMemberPathConfiguration.cs
  src/Riok.Mapperly/Configuration/StringMemberPath.cs
  src/Riok.Mapperly/Configuration/SymbolMemberPath.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/IMembersBuilderContext.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingState.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingStateBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs
  src/Riok.Mapperly/Helpers/ListDictionary.cs
  src/Riok.Mapperly/Symbols/Members/MemberPath.cs
  src/Riok.Mapperly/Symbols/Members/NonEmptyMemberPath.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
  test/Riok.Mapperly.Tests/Mapping/ValueTupleTest.cs
Labels: bug

#1561 docs: allow cloudflare insights in docs csp
  docs/static/_headers
Labels: no-changelog

#1562 fix: correctly handle mapping to read-only target arrays
  src/Riok.Mapperly/Descriptors/Mappings/NoOpMapping.cs
  test/Riok.Mapperly.Tests/Mapping/EnumerableExistingTargetTest.cs
  test/Riok.Mapperly.Tests/_snapshots/EnumerableExistingTargetTest.MapArrayToReadOnlyArrayShouldDiagnostic#Mapper.g.verified.cs
  test/Riok.Mapperly.Tests/_snapshots/EnumerableExistingTargetTest.MapArrayToReadOnlyArrayShouldDiagnostic.verified.txt
Labels: bug

#1563 fix: lazy load types which are not available on netstandard2.0
  src/Riok.Mapperly/Descriptors/Enumerables/CollectionInfoBuilder.cs
Labels: bug

#1570 fix: existing target unmapped required member should not lead to error diagnostic
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MemberMappingDiagnosticReporter.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/EnumerableMappingBodyBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewValueTupleMappingBodyBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyExistingInstanceTest.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyExistingInstanceTest.UnmappedRequiredPropertyShouldDiagnostic#Mapper.g.verified.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyExistingInstanceTest.UnmappedRequiredPropertyShouldDiagnostic.verified.txt
Labels: bug
