Repository riok/mapperly, pull requests merged in 2024-08, with the labels that each got.

#1434 Upgrade dotnet
  global.json
Labels: dependencies

#1435 Upgrade xml2doc
  .config/dotnet-tools.json
  docs/prebuild.ts
Labels: enhancement

#1436 Upgrade junit logger
  test/Directory.Build.props
Labels: dependencies

#1437 Upgrade docusaurus
  docs/package-lock.json
  docs/package.json
Labels: dependencies

#1418 Fix failing projection with static mapper from another assembly
  src/Riok.Mapperly/Descriptors/MappingBuilders/InlineExpressionMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/SimpleMappingBuilderContext.cs
  src/Riok.Mapperly/Helpers/IncrementalValuesProviderExtensions.cs
  src/Riok.Mapperly/MapperGenerator.cs
  src/Riok.Mapperly/Symbols/CompilationContext.cs
  src/Riok.Mapperly/SyntaxProvider.Roslyn4.0.cs
  src/Riok.Mapperly/SyntaxProvider.Roslyn4.4.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/UseExternalMapperFromAnotherAssemblyTest.SnapshotGeneratedSource.verified.cs
  test/Riok.Mapperly.Tests/Helpers/GenericTypeCheckerTest.cs
  test/Riok.Mapperly.Tests/Mapping/UseStaticMapperTest.cs
  test/Riok.Mapperly.Tests/TestAssembly.cs
  test/Riok.Mapperly.Tests/TestHelper.cs
Labels: bug

#1419 Support inline expression with casting
  src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs
  test/Riok.Mapperly.Tests/Helpers/InlineExpressionRewriterTest.cs
Labels: bug

#1404 fix: correct map nested interfaced enumerations
  src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/Mappings/ArrayForEachMapping.cs
  src/Riok.Mapperly/Descriptors/Mappings/ArrayForMapping.cs
  src/Riok.Mapperly/Emit/Syntax/SyntaxFactoryHelper.Array.cs
  test/Riok.Mapperly.IntegrationTests/Mapper/StaticTestMapper.cs
  test/Riok.Mapperly.IntegrationTests/StaticMapperTest.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.SnapshotGeneratedSource.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.SnapshotGeneratedSource_NET6_0.verified.cs
  test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
  test/Riok.Mapperly.Tests/_snapshots/EnumerableTest.NestedInterfacedLists#Mapper.g.verified.cs
Labels: bug

#1408 fix: only initialize unflattened nullable target members when needed
  docs/docs/breaking-changes/4-0.md
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersContainerBuilderContext.cs
  src/Riok.Mapperly/Descriptors/Mappings/MemberMappings/IAssignmentMappings.cs
  src/Riok.Mapperly/Descriptors/Mappings/MemberMappings/IMemberAssignmentMapping.cs
  src/Riok.Mapperly/Descriptors/Mappings/MemberMappings/IMemberAssignmentMappingContainer.cs
  src/Riok.Mapperly/Descriptors/Mappings/MemberMappings/MemberAssignmentMappingContainer.cs
  src/Riok.Mapperly/Descriptors/Mappings/MemberMappings/MemberMappingInfo.cs
  src/Riok.Mapperly/Descriptors/Mappings/MemberMappings/SourceValue/MappedMemberSourceValue.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/CircularReferenceMapperTest.SnapshotGeneratedSource.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/DeepCloningMapperTest.SnapshotGeneratedSource.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/DeepCloningMapperTest.SnapshotGeneratedSource_NET6_0.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/MapperTest.SnapshotGeneratedSource.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/MapperTest.SnapshotGeneratedSource_NET6_0.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/MapperTest.SnapshotGeneratedSource_NET8_0.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/ProjectionMapperTest.SnapshotGeneratedSource.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/ProjectionMapperTest.SnapshotGeneratedSource_NET6_0.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.SnapshotGeneratedSource.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.SnapshotGeneratedSource_NET6_0.verified.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyNullableTest.NullableIntWithAdditionalFlattenedValueToNonNullableIntProperties#Mapper.g.verified.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyUseNamedMappingTest.ShouldPassNullValueToNullableUserMappingMethod#Mapper.g.verified.cs
  test/Riok.Mapperly.Tests/_snapshots/UserMethodAdditionalParametersTest.AdditionalNullableIntParameter#Mapper.g.verified.cs
Labels: bug

#1413 fix: improve handling of read-only and immutable types
  docs/docs/breaking-changes/4-0.md
  src/Riok.Mapperly/AnalyzerReleases.Shipped.md
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/MemoryMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/NewInstanceObjectMemberMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/SpanMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/Mappings/MemberMappings/MemberMappingInfo.cs
  src/Riok.Mapperly/Descriptors/Mappings/NoOpMapping.cs
  src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs
  src/Riok.Mapperly/Helpers/SymbolExtensions.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/DeepCloningMapperTest.RunMappingShouldWork.verified.txt
  test/Riok.Mapperly.IntegrationTests/_snapshots/DeepCloningMapperTest.RunMappingShouldWork_NET6_0.verified.txt
  test/Riok.Mapperly.IntegrationTests/_snapshots/DeepCloningMapperTest.SnapshotGeneratedSource.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/DeepCloningMapperTest.SnapshotGeneratedSource_NET6_0.verified.cs
  test/Riok.Mapperly.Tests/Mapping/DictionaryCustomTest.cs
  test/Riok.Mapperly.Tests/Mapping/DictionaryImmutableTest.cs
  test/Riok.Mapperly.Tests/Mapping/DictionaryTest.cs
  test/Riok.Mapperly.Tests/Mapping/DirectAssignmentDeepCloningTest.cs
  test/Riok.Mapperly.Tests/Mapping/EnumerableImmutableTest.cs
  test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
  test/Riok.Mapperly.Tests/Mapping/MemoryTest.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyExistingInstanceTest.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
  test/Riok.Mapperly.Tests/Mapping/SpanTest.cs
  test/Riok.Mapperly.Tests/Mapping/UnsafeAccessorTest.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.ShouldIgnoreReadOnlyPropertyOnTargetWithDiagnostic.verified.txt
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.ShouldIgnoreReadOnlyPropertyWhenMatchedAutomatically#Mapper.g.verified.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateTargetPathGetterShouldIgnoreAndDiagnostic#Mapper.g.verified.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateTargetPathGetterShouldIgnoreAndDiagnostic.verified.txt
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateTargetSetterShouldIgnoreAndDiagnostic#Mapper.g.verified.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateTargetSetterShouldIgnoreAndDiagnostic.verified.txt
Labels: bug, enhancement, breaking-change

#1447 fix: improve member matching performance for member names with lots of upper case letters
  docs/docs/breaking-changes/4-0.md
  src/Riok.Mapperly/Configuration/StringMemberPath.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/NestedMappingsContext.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/NewValueTupleConstructorBuilderContext.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/NewValueTupleExpressionBuilderContext.cs
  src/Riok.Mapperly/Descriptors/MemberPathCandidateBuilder.cs
  src/Riok.Mapperly/Descriptors/SymbolAccessor.cs
  src/Riok.Mapperly/Helpers/ImmutableEquatableArray.cs
  test/Riok.Mapperly.Tests/Descriptors/MemberPathCandidateBuilderTest.cs
Labels: bug, breaking-change

#1449 fix: initialize nullable values when assigning null to a child member
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersContainerBuilderContext.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNullableTest.cs
Labels: bug

#1462 fix: report inaccessible constructor instead of mapping could not be created
  src/Riok.Mapperly/Descriptors/MappingBuilders/ExistingTargetMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/MappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/NewInstanceObjectMemberMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/Mappings/NewValueTupleExpressionMapping.cs
  src/Riok.Mapperly/Descriptors/Mappings/UnimplementedMapping.cs
  src/Riok.Mapperly/Descriptors/Mappings/UserMappings/UserDefinedExistingTargetMethodMapping.cs
  src/Riok.Mapperly/Descriptors/Mappings/UserMappings/UserDefinedNewInstanceMethodMapping.cs
  src/Riok.Mapperly/Emit/Syntax/SyntaxFactoryHelper.Exception.cs
  test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
  test/Riok.Mapperly.Tests/Mapping/ReferenceHandlingTest.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyConstructorResolverTest.ClassToClassPrivateCtorShouldDiagnostic.verified.txt
Labels: bug

#1463 improve bugfix issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: no-changelog

#1464 Adding support for mappers being nested under interfaces or records
  src/Riok.Mapperly/Emit/SourceEmitter.cs
  src/Riok.Mapperly/Emit/Syntax/SyntaxFactoryHelper.SymbolDeclaration.cs
  test/Riok.Mapperly.IntegrationTests/Mapper/INestedTestMapper.cs
  test/Riok.Mapperly.IntegrationTests/Mapper/NestedTestMapperPrimaryConstructor.cs
  test/Riok.Mapperly.IntegrationTests/Mapper/NestedTestMapperRecord.cs
  test/Riok.Mapperly.IntegrationTests/NestedMapperInterfaceTest.cs
  test/Riok.Mapperly.IntegrationTests/NestedMapperPrimaryConstructorTest.cs
  test/Riok.Mapperly.IntegrationTests/NestedMapperRecordTest.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/NestedMapperInterfaceTest.SnapshotGeneratedSource.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/NestedMapperPrimaryConstructorTest.SnapshotGeneratedSource.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/NestedMapperRecordTest.SnapshotGeneratedSource.verified.cs
Labels: enhancement
