Repository riok/mapperly, pull requests merged in 2025-07, with the labels that each got.

#1886 Fix syntax errors in tests
  test/Riok.Mapperly.Tests/Mapping/IncludeMappingConfigurationTest.cs
  test/Riok.Mapperly.Tests/Mapping/NamedMappingTest.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs
Labels: no-changelog

#1893 docs: add info that derived type mappings do not support additional type parameters
  docs/docs/configuration/additional-mapping-parameters.mdx
Labels: documentation

#1894 docs: improve fullnameof docs
  docs/docs/configuration/flattening.md
Labels: documentation

#1903 chore: upgrade minor dotnet dependencies
  .config/dotnet-tools.json
  src/Directory.Build.props
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingState.cs
  src/Riok.Mapperly/Riok.Mapperly.csproj
  test/Riok.Mapperly.IntegrationTests/Riok.Mapperly.IntegrationTests.csproj
Labels: dependencies, .NET, no-changelog
