Repository riok/mapperly, pull requests merged in 2025-04, with the labels that each got.

#1789 fix: add value suffix when getting non-enumerated count on nullable value types
  src/Riok.Mapperly/Descriptors/Mappings/ExistingTarget/NullDelegateExistingTargetMapping.cs
  test/Riok.Mapperly.Tests/Mapping/EnumerableExistingTargetTest.cs
Labels: bug

#1790 fix: fixes queryable projection inlining of user-defined mappings calling generated mappings
  src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs
  test/Riok.Mapperly.Tests/Mapping/QueryableProjectionUserImplementedTest.cs
  test/Riok.Mapperly.Tests/_snapshots/QueryableProjectionUserImplementedTest.UserImplementedFlatteningWithCallToAnotherMapping#Mapper.g.verified.cs
Labels: bug

#1791 chore: add gh repro to template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: no-changelog

#1806 fix(doc): In page "contributing", replace remaining occurence of "OpenThread"
  docs/docs/contributing/index.md
Labels: documentation

#1809 chore: upgrade docs npm dependencies
  docs/package-lock.json
  docs/package.json
  docs/src/components/AnalyzerRules.tsx
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/NavbarItems/CoffeeNavbarItem/index.tsx
  docs/src/components/NavbarItems/VersionsNavbarItem/index.tsx
  docs/src/css/custom.css
  docs/src/pages/index.tsx
Labels: documentation, no-changelog

#1810 fix: correct nullable handling in queryable projection mappings with nullable value types and custom mapping methods
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/MemberMappingBuilder.cs
  test/Riok.Mapperly.IntegrationTests/Dto/TestObjectDtoProjection.cs
  test/Riok.Mapperly.IntegrationTests/Mapper/ProjectionMapper.cs
  test/Riok.Mapperly.IntegrationTests/Models/TestObjectProjection.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/ProjectionMapperTest.ProjectionShouldTranslateToQuery.verified.sql
  test/Riok.Mapperly.IntegrationTests/_snapshots/ProjectionMapperTest.ProjectionShouldTranslateToQuery_NET8_0.verified.sql
  test/Riok.Mapperly.IntegrationTests/_snapshots/ProjectionMapperTest.ProjectionShouldTranslateToQuery_NET9_0.verified.sql
  test/Riok.Mapperly.IntegrationTests/_snapshots/ProjectionMapperTest.ProjectionShouldTranslateToResult.verified.txt
  test/Riok.Mapperly.IntegrationTests/_snapshots/ProjectionMapperTest.SnapshotGeneratedSource.verified.cs
  test/Riok.Mapperly.IntegrationTests/_snapshots/ProjectionMapperTest.SnapshotGeneratedSource_NET6_0.verified.cs
  test/Riok.Mapperly.Tests/Mapping/QueryableProjectionUserImplementedTest.cs
  test/Riok.Mapperly.Tests/_snapshots/QueryableProjectionUserImplementedTest.UserImplementedNullableValueTypeToNonNullable#Mapper.g.verified.cs
Labels: bug

#1811 fix: resolve base methods in MapValue.Use
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/SourceValueBuilder.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyValueMethodTest.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyValueMethodTest.BaseClassProtectedMethodToProperty#Mapper.g.verified.cs
Labels: bug

#1812 fix: resolve base mappings in MapProperty.Use
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/SourceValueBuilder.cs
  src/Riok.Mapperly/Descriptors/SymbolAccessor.cs
  src/Riok.Mapperly/Descriptors/UserMethodMappingExtractor.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyUseNamedMappingTest.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyUseNamedMappingTest.BaseClassProtectedMethodToProperty#Mapper.g.verified.cs
Labels: bug

#1813 fix: resolve object factories in base classes
  src/Riok.Mapperly/Descriptors/ObjectFactories/ObjectFactoryBuilder.cs
  src/Riok.Mapperly/Descriptors/SymbolAccessor.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectFactoryTest.cs
  test/Riok.Mapperly.Tests/_snapshots/ObjectFactoryTest.ShouldUseSimpleObjectFactoryOfBaseClass#Mapper.g.verified.cs
Labels: bug
