Repository riok/mapperly, pull requests merged in 2025-05, with the labels that each got.

#1834 docs: add failing test option to repro in bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#1836 fix typo: dontet -> dotnet
  docs/docs/contributing/docs.md
  docs/docs/getting-started/installation.mdx
Labels: documentation

#1835 fix: nullable user implemented value type mappings in queryable projections
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/MemberMappingBuilder.cs
  test/Riok.Mapperly.Tests/Mapping/QueryableProjectionUserImplementedTest.cs
  test/Riok.Mapperly.Tests/_snapshots/QueryableProjectionUserImplementedTest.UserImplementedAttributedNullableValueTypeToNullable#Mapper.g.verified.cs
  test/Riok.Mapperly.Tests/_snapshots/QueryableProjectionUserImplementedTest.UserImplementedAttributedNullableValueTypeToNullableMemberTypeMismatch#Mapper.g.verified.cs
  test/Riok.Mapperly.Tests/_snapshots/QueryableProjectionUserImplementedTest.UserImplementedAttributedNullableValueTypeToNullableMemberTypeMismatch.verified.txt
Labels: bug

#1804 feat: Allow to disable null mismatch diagnostics RMG089 per member
  src/Riok.Mapperly.Abstractions/MapPropertyAttribute.cs
  src/Riok.Mapperly/Configuration/MemberMappingConfiguration.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/MemberMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/TypeMappingConfiguration.cs
  src/Riok.Mapperly/MapperGenerator.cs
  test/Riok.Mapperly.Abstractions.Tests/_snapshots/PublicApiTest.PublicApiHasNotChanged.verified.cs
  test/Riok.Mapperly.IntegrationTests/Models/ExistingObjectBase.cs
  test/Riok.Mapperly.IntegrationTests/Models/ExistingObjectTypeA.cs
  test/Riok.Mapperly.IntegrationTests/Models/ExistingObjectTypeB.cs
  test/Riok.Mapperly.IntegrationTests/NestedMapperInterfaceTest.cs
  test/Riok.Mapperly.IntegrationTests/NestedMapperPrimaryConstructorTest.cs
  test/Riok.Mapperly.IntegrationTests/NestedMapperRecordTest.cs
  test/Riok.Mapperly.Tests/Mapping/ExtensionMethodTest.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs
Labels: enhancement
