Repository riok/mapperly, pull requests merged in 2025-10, with the labels that each got.

#1966 fix: correctly inline user-defined nested queryable projection mappings
  src/Riok.Mapperly/Descriptors/InlineExpressionMappingBuilderContext.cs
  src/Riok.Mapperly/Descriptors/InlinedExpressionMappingCollection.cs
  test/Riok.Mapperly.Tests/Mapping/QueryableProjectionUserImplementedTest.cs
  test/Riok.Mapperly.Tests/_snapshots/QueryableProjectionUserImplementedTest.UserImplementedTwoNestedProjectionsShouldReuseInlinedMapping#Mapper.g.verified.cs
  test/Riok.Mapperly.Tests/_snapshots/QueryableProjectionUserImplementedTest.UserImplementedTwoProjectionsShouldReuseInlinedMapping#Mapper.g.verified.cs
  test/Riok.Mapperly.Tests/_snapshots/QueryableProjectionUserImplementedTest.UserImplementedTwoProjectionsShouldReuseInlinedMapping.verified.txt
  test/Riok.Mapperly.Tests/_snapshots/UseMapperTest.UseMapper.verified.txt
Labels: bug

#1941 Add support for ignoring static convert methods with MapperIgnore
  docs/docs/configuration/conversions.md
  docs/docs/configuration/mapper.mdx
  src/Riok.Mapperly.Abstractions/MapperIgnoreAttribute.cs
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingStateBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/ConvertInstanceMethodMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/ConvertStaticMethodMappingBuilder.cs
  src/Riok.Mapperly/Descriptors/MappingBuilders/ParseMappingBuilder.cs
  test/Riok.Mapperly.Abstractions.Tests/_snapshots/PublicApiTest.PublicApiHasNotChanged.verified.cs
  test/Riok.Mapperly.Tests/Mapping/ParseTest.cs
  test/Riok.Mapperly.Tests/Mapping/StaticMethodConversionTest.cs
  test/Riok.Mapperly.Tests/Mapping/ToTargetInstanceTest.cs
Labels: enhancement

#1977 docs: use a main page for external mappings
  docs/docs/configuration/analyzer-diagnostics/index.mdx
  docs/docs/configuration/conversions.md
  docs/docs/configuration/derived-type-mapping.md
  docs/docs/configuration/existing-target.mdx
  docs/docs/configuration/external-mappings.mdx
  docs/docs/configuration/flattening.md
  docs/docs/configuration/full-nameof.md
  docs/docs/configuration/generated-source.mdx
  docs/docs/configuration/generic-mapping.md
  docs/docs/configuration/mapper.mdx
  docs/docs/configuration/private-members.mdx
  docs/docs/configuration/queryable-projections.mdx
  docs/docs/configuration/reference-handling.md
  docs/docs/configuration/reusing-mapping-configurations.mdx
  docs/docs/configuration/user-implemented-methods.mdx
  src/Riok.Mapperly/Descriptors/Mappings/ExistingTarget/NullDelegateExistingTargetMapping.cs
  src/Riok.Mapperly/Descriptors/Mappings/NullDelegateMapping.cs
  src/Riok.Mapperly/Symbols/Members/MemberPathGetter.cs
Labels: documentation
