Repository riok/mapperly, pull requests merged in 2025-01, with the labels that each got.

#1671 Update RMG060.mdx
  docs/docs/configuration/analyzer-diagnostics/RMG060.mdx
Labels: documentation

#1681 chore(CI): rm dotnet-validate since it is unmaintained
  .config/dotnet-tools.json
  .github/workflows/test.yml
Labels: no-changelog

#1660 fix: initialize nullable members for nested containers
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersContainerBuilderContext.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNullableTest.cs
Labels: bug

#1686 fix: only diagnostic missing member mappings for required init members
  src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs
  test/Riok.Mapperly.Tests/Mapping/ObjectPropertyInitPropertyTest.cs
Labels: bug

#1688 add security policy
  SECURITY.md
Labels: no-changelog
